<wsdl:definitions
     name="FindCountriesDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataService/CountryService/FindCountriesDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataService/CountryService/FindCountriesDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/FindCountriesDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="FindCountriesDB_plt" >
    <plt:role name="FindCountriesDB_role" >
      <plt:portType name="tns:FindCountriesDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/FindCountriesDB" schemaLocation="FindCountriesDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="FindCountriesDBSelect_inputParameters">
        <wsdl:part name="FindCountriesDBSelect_inputParameters" element="top:FindCountriesDBSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CmnCountriesCollection_msg">
        <wsdl:part name="CmnCountriesCollection" element="top:CmnCountriesCollection"/>
    </wsdl:message>
    <wsdl:portType name="FindCountriesDB_ptt">
        <wsdl:operation name="FindCountriesDBSelect">
            <wsdl:input message="tns:FindCountriesDBSelect_inputParameters"/>
            <wsdl:output message="tns:CmnCountriesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
