<wsdl:definitions
     name="GetCountryDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataService/CountryService/GetCountryDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataService/CountryService/GetCountryDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetCountryDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="GetCountryDB_plt" >
    <plt:role name="GetCountryDB_role" >
      <plt:portType name="tns:GetCountryDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetCountryDB" schemaLocation="GetCountryDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:CmnCountriesPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="CmnCountriesCollection_msg">
        <wsdl:part name="CmnCountriesCollection" element="top:CmnCountriesCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetCountryDB_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:CmnCountriesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
